
json.extract! product,
    :id,
    :name,
    :category,
    :sub_category,
    :description,
    :size,
    :price,
    :key_ingredients,
    :how_to_use,
    :dosage,
    :texture,
    :aroma,
    :suited_to,
    :skin_feel,
    :skin_type,
    :skin_concern,
    :scalp_type,
    :hair_type,
    :application,
    :scent_profile,
    :about_this_kit

